version: '3.8'
services:
  reverseproxy:
    image: jwilder/nginx-proxy

    container_name: reverseproxy

    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # Red para el conjunto de contenedores            
    networks:
      - net-prueba
    restart: always
    privileged: true
  
  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./back/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-prueba 
    depends_on: 
      - reverseproxy
  
  angular:
    build: front/
    container_name: angular    
    volumes:
      - ./front/bolsa_trabajo_front/:/app
    environment: 
      - VIRTUAL_HOST=prueba1.com
    networks:
      - net-prueba 
    depends_on: 
      - reverseproxy
  
  php-fpm:
    build: ./php-fpm
    container_name: php-fpm
    working_dir: /application
    volumes:
    - ./bolsa_trabajo_front:/application
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - net-prueba   
    depends_on: 
      - reverseproxy
  
  phpmyadmin:
    build: phpmyadmin
    container_name: phpmyadmin
    restart: always
    networks:
      - net-prueba 
    depends_on: 
      - db
      - reverseproxy
    environment: 
      - VIRTUAL_HOST=phpmyadmin.com  
    networks:
      - net-prueba    
    
  db:
    image: mariadb:10.5.8
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_USER: admin      
    # volumes:
    #   - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - net-prueba

networks:
  net-prueba:
    driver: bridge