version: '3.8'
services:
  reverseproxy:
    image: jwilder/nginx-proxy

    container_name: reverseproxy

    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # Red para el conjunto de contenedores            
    networks:
      - net-prueba
    restart: always
    privileged: true
  
  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./back/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment: 
      - VIRTUAL_HOST=prueba1.com
    networks:
      - net-prueba 
  
  php-fpm:
    build: back/php-fpm
    container_name: php-fpm
    working_dir: /application
    volumes:
    - ./back/my-cool-app:/application
    - ./back/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    networks:
      - net-prueba    
  
#   db:
#     image: mysql:5.7
#     container_name: travellist-db
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       MYSQL_USER: ${DB_USERNAME}
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql
#     volumes:
#       - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#     networks:
#       - travellist

networks:
  net-prueba:
    driver: bridge